- name: Install Python
  apt: name={{item}} state=present
  with_items:
    - python2.7
    - python2.7-dev
    - python-pip


- name: Install virtualenv
  pip: name={{item}}
  with_items:
    - virtualenv
    - virtualenvwrapper